import { LoginContext } from '../contexts/handleLogin.js';
import { createClient } from '@supabase/supabase-js';
import { useState, useContext } from 'react';
import { useRouter } from 'next/router';
import { ethers } from 'ethers';
import Head from 'next/head';
import Link from 'next/link';
import Web3 from 'web3';

export async function getServerSideProps(props) {
    return {
        props: {
            CONNECTION: process.env.CONNECTION,
            S_URL: process.env.SUPABASE_URL,
            KEY: process.env.SUPABASE_ANON_KEY,
            ADDRESS: process.env.CONTRACT_ADDRESS
        }
    }
}

export default function Mint({CONNECTION, S_URL, KEY, ADDRESS}) {
    const {isLoggedIn, substringAccount, Connect} = useContext(LoginContext);
    const [formInput, updateFormInput] = useState({name: '', imageURL: ''});
    const [errorMessages, setErrorMessages] = useState([]);
    const [isLoading, setIsLoading] = useState(false); 
    const router = useRouter();

    async function MintSlot(e) {
        e.preventDefault();

        const {name, imageURL} = formInput;
        let messages = [];

        if(name.trim() === "" || name == null) {
            messages.push("Name is required")
        }
      
        if(name.length > 23) {
            messages.push("Name must be less than 23 characters")
        }
      
        if(imageURL.trim() === "" || imageURL == null) {
        messages.push("Image URL is required")
        }
      
        if(imageURL.length > 300) {
            messages.push("Image URL must be less than 300 characters")
        }
      
        try {
            new URL(imageURL);
        } catch (e) {
            messages.push("Image URL must be a valid URL") 
        }

        if(messages.length > 0) {
            setErrorMessages(messages)
            document.getElementById("errorModal").classList.remove("hidden"); 
        } else {
            setIsLoading(true);
        
            const contractABI = require('/contracts/abi.json'); // CONTRACT ABI
        
            const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' }); // REQUEST CONNECTED ACCOUNT FROM METAMASK
            const account = ethers.utils.getAddress(accounts[0]); // SET CONNECTED ACCOUNT
        
            const web3 = new Web3(new Web3.providers.HttpProvider(CONNECTION)); // PROVIDER CONNECTION
            const contract = new web3.eth.Contract(contractABI, ADDRESS); // CREATING CONTRACT
        
            const numSlots = await contract.methods.numSlots().call(); // FETCHING THE NUMBER OF SLOTS
            const mintPrice = await contract.methods.mintPrice().call(); // FETCHING THE NUMBER OF SLOTS

            console.log('mint price: ' + mintPrice)
        
            const seed = Math.floor(Math.random() * 1000) + 1; // GENERATING THE SEED
        
            const transaction = await contract.methods.Mint(seed).send({ // MAKING TRANSACTION AND CREATING SLOT
                from: account,
                to: ADDRESS,
                gasLimit: 3000001,
                value: mintPrice,
            });
        
            // SAVING SLOT DATA IN SUPABASE
            const { data, error } = await createClient(S_URL, KEY).from('Adressess').insert([{imageURL: imageURL, name: name, verified: false, slot: numSlots, address: account, seed: seed},])
            
           router.push('/address/' + ethers.utils.getAddress(account))
        }
    }

    async function closeWarning() {
        document.getElementById("errorModal").classList.add("hidden");
    }

  return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div id='errorModal' className='bg-black bg-opacity-75 min-h-screen w-full flex justify-center items-center fixed hidden z-10'>
            <section className='flex justify-center'>
                <div className='max-w-md w-full bg-white rounded border-black border-2 p-5'>
                    {errorMessages.map((errorMessages, key) => (
                        <p key={key} className='mb-5'>&#128204; {errorMessages} !</p>
                    ))}
                    <button onClick={closeWarning} className='w-full'>
                        <div className='bg-black cursor-pointer'>
                            <div className='border-black border-2 bg-color-1 p-2 transition ease-in-out duration-200 hover:-translate-x-1 hover:-translate-y-1'>
                                <h1>X</h1>
                            </div>
                        </div>
                    </button>
                </div>
            </section>
        </div>

        <div className='min-h-screen bg-blue-100 grid place-items-center'>
            <section className='grid place-items-center'>
                {substringAccount ?
                    <div className='rounded-xl bg-black'>
                        <div className='p-5 border-black border-2 rounded-xl bg-white -translate-x-1 -translate-y-1'>
                            <p className='mb-1'>Hi, {substringAccount}</p>
                            <h1 className='text-3xl mb-5'>Get started!</h1>
                            <form onSubmit={MintSlot} className='flex flex-col gap-3'>
                                <input placeholder='Name' className='border-black border-2 p-2' onChange={e => updateFormInput({ ...formInput, name: e.target.value })}/>
                                <input placeholder='Image URL' className='border-black border-2 p-2' onChange={e => updateFormInput({ ...formInput, imageURL: e.target.value })}/>
                                <p className='my-2'>By minting a slot you agree with the <Link href="/about"><span className='underline cursor-pointer'>Terms of Use</span></Link></p>
                                <button type='submit'>
                                    <div className='bg-black cursor-pointer'>
                                        <div className='border-black border-2 bg-color-2 p-2 transition ease-in-out duration-200 hover:-translate-x-1 hover:-translate-y-1'>
                                            <h1>Mint</h1>
                                        </div>
                                    </div>
                                </button>
                            </form>
                        </div>
                    </div>
                    :
                    <div className='grid place-items-center'>
                        <p>Mint yout slot right know</p>
                        <h1 className='text-4xl mb-5'>You need to connect you wallet!</h1>
                        <button onClick={Connect}>
                            <div className='bg-black w-40 text-center cursor-pointer'>
                                <div className='border-black border-2 bg-white p-2 transition ease-in-out duration-200 hover:-translate-x-1 hover:-translate-y-1'>
                                    <h1>Connect Wallet</h1>
                                </div>
                            </div>
                        </button>
                    </div>
                }
            </section>
        </div>
    </>
  )
}
